#!/bin/bash -e

declare _mydir=$(dirname $0)
source "${_mydir}"/env.rc
source "${_mydir}"/util.rc

main() {

    if [ -f "${_build_context}/${_scrap_demand_stop_building}" ] ; then
        echo "Skipping build on demand."
        return 0
    fi

    local now
    local version_sticker

    if [ -f "${_build_context}/${_scrap_version_sticker_current}" ] ; then
        version_sticker="$( cat ${_build_context}/${_scrap_version_sticker_current} )"
    else
        version_sticker="null"
    fi

    now="$(date --utc +%FT%TZ)"
    echo "Current timestamp: ${now}" ; echo

    case "${_blend}" in

        ### -------------------------
        ### ubuntu-vnc-xfce-nodejs-g3
        ### -------------------------

        nodejs-vnc* | nodejs-current-vnc* | latest-nodejs )

            set -x
            docker build $@ \
                -f "${DOCKERFILE_PATH}" \
                    --build-arg BUILDKIT_INLINE_CACHE=1 \
                    --build-arg BASEIMAGE="${BASEIMAGE}" \
                    --build-arg BASETAG="${BASETAG}" \
                    --build-arg ARG_CREATED="${now}" \
                    --build-arg ARG_DOCKER_TAG=${DOCKER_TAG} \
                    --build-arg ARG_VERSION_STICKER="${version_sticker}" \
                    --build-arg ARG_VCS_REF="$(git rev-parse --short HEAD)" \
                    \
                    ${FEATURES_BUILD_SLIM:+--build-arg ARG_APT_NO_RECOMMENDS=1} \
                    ${FEATURES_SCREENSHOOTING:+--build-arg ARG_FEATURES_SCREENSHOOTING=1} \
                    ${FEATURES_THUMBNAILING:+--build-arg ARG_FEATURES_THUMBNAILING=1} \
                    ${FEATURES_USER_GROUP_OVERRIDE:+--build-arg ARG_FEATURES_USER_GROUP_OVERRIDE=1} \
                    \
                    ${FEATURES_NOVNC:+--build-arg ARG_MERGE_STAGE_VNC_BASE="stage_novnc"} \
                    \
                    ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_VERSION=${CHROMIUM_VERSION}} \
                    ${FEATURES_CHROMIUM:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_chromium"} \
                    \
                    ${FEATURES_FIREFOX:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox"} \
                    ${FEATURES_FIREFOX_PLUS:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox_plus"} \
                    \
                    ${NODEJS_VERSION:+--build-arg ARG_NODEJS_VERSION=${NODEJS_VERSION}} \
                    ${FEATURES_NODEJS:+--build-arg ARG_FINAL_STAGE_BASE="stage_nodejs"} \
                    \
                    ${FEATURES_VSCODE:+--build-arg ARG_FINAL_STAGE_BASE="stage_vscode"} \
                    \
                -t "${DOCKER_REPO}":"${DOCKER_TAG}" "${_build_context}"
            set +x
            ;;

        ### -------------------------
        ### ubuntu-vnc-xfce-python-g3
        ### -------------------------

        python-vnc* | latest-python )

            set -x
            docker build $@ \
                -f "${DOCKERFILE_PATH}" \
                    --build-arg BUILDKIT_INLINE_CACHE=1 \
                    --build-arg BASEIMAGE="${BASEIMAGE}" \
                    --build-arg BASETAG="${BASETAG}" \
                    --build-arg ARG_CREATED="${now}" \
                    --build-arg ARG_DOCKER_TAG=${DOCKER_TAG} \
                    --build-arg ARG_VERSION_STICKER="${version_sticker}" \
                    --build-arg ARG_VCS_REF="$(git rev-parse --short HEAD)" \
                    \
                    ${FEATURES_BUILD_SLIM:+--build-arg ARG_APT_NO_RECOMMENDS=1} \
                    ${FEATURES_SCREENSHOOTING:+--build-arg ARG_FEATURES_SCREENSHOOTING=1} \
                    ${FEATURES_THUMBNAILING:+--build-arg ARG_FEATURES_THUMBNAILING=1} \
                    ${FEATURES_USER_GROUP_OVERRIDE:+--build-arg ARG_FEATURES_USER_GROUP_OVERRIDE=1} \
                    \
                    ${FEATURES_NOVNC:+--build-arg ARG_MERGE_STAGE_VNC_BASE="stage_novnc"} \
                    \
                    ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_VERSION=${CHROMIUM_VERSION}} \
                    ${FEATURES_CHROMIUM:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_chromium"} \
                    \
                    ${FEATURES_FIREFOX:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox"} \
                    ${FEATURES_FIREFOX_PLUS:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox_plus"} \
                    \
                    ${FEATURES_PYTHON_KIVY:+--build-arg ARG_MERGE_STAGE_PYTHON_BASE="stage_python_kivy"} \
                    ${FEATURES_PYTHON_PYQT5:+--build-arg ARG_MERGE_STAGE_PYTHON_BASE="stage_python_pyqt5"} \
                    ${FEATURES_PYTHON_PYSIDE2:+--build-arg ARG_MERGE_STAGE_PYTHON_BASE="stage_python_pyside2"} \
                    ${FEATURES_PYTHON_TKINTER:+--build-arg ARG_MERGE_STAGE_PYTHON_BASE="stage_python_tkinter"} \
                    ${FEATURES_PYTHON_WXPYTHON:+--build-arg ARG_MERGE_STAGE_PYTHON_BASE="stage_python_wxpython"} \
                    \
                    ${FEATURES_PYTHON:+--build-arg ARG_FINAL_STAGE_BASE="merge_stage_pyton"} \
                    ${FEATURES_VSCODE:+--build-arg ARG_FINAL_STAGE_BASE="stage_vscode"} \
                    \
                -t "${DOCKER_REPO}":"${DOCKER_TAG}" "${_build_context}"
            set +x
            ;;
            
        ### --------------------------------
        ### headless-coding-g3 (base images)
        ### --------------------------------

        ### These base images will not be built or published on Docker Hub.

        xfce-vnc* )

            set -x
            docker build $@ \
                -f "${DOCKERFILE_PATH}" \
                    --build-arg BUILDKIT_INLINE_CACHE=1 \
                    --build-arg BASEIMAGE="${BASEIMAGE}" \
                    --build-arg BASETAG="${BASETAG}" \
                    --build-arg ARG_CREATED="${now}" \
                    --build-arg ARG_DOCKER_TAG=${DOCKER_TAG} \
                    --build-arg ARG_VERSION_STICKER="${version_sticker}" \
                    --build-arg ARG_VCS_REF="$(git rev-parse --short HEAD)" \
                    \
                    ${FEATURES_BUILD_SLIM:+--build-arg ARG_APT_NO_RECOMMENDS=1} \
                    ${FEATURES_SCREENSHOOTING:+--build-arg ARG_FEATURES_SCREENSHOOTING=1} \
                    ${FEATURES_THUMBNAILING:+--build-arg ARG_FEATURES_THUMBNAILING=1} \
                    ${FEATURES_USER_GROUP_OVERRIDE:+--build-arg ARG_FEATURES_USER_GROUP_OVERRIDE=1} \
                    \
                    ${FEATURES_NOVNC:+--build-arg ARG_MERGE_STAGE_VNC_BASE="stage_novnc"} \
                    \
                    ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_VERSION=${CHROMIUM_VERSION}} \
                    ${FEATURES_CHROMIUM:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_chromium"} \
                    \
                    ${FEATURES_FIREFOX:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox"} \
                    ${FEATURES_FIREFOX_PLUS:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox_plus"} \
                    \
                -t "${DOCKER_REPO}":"${DOCKER_TAG}" "${_build_context}"
            set +x
            ;;

        * )
            echo "Cannot build unknown blend '${_blend}'"
            retutn 1
            ;;
    esac
}

main $@
