#!/bin/bash

main() {
    local result=""

    case "$1" in

        nodejs-current )
            # result=$(wget -qO- \
            result=$(curl -sLN \
                https://nodejs.org/en/download/current/ \
                | grep -Po -m1 '(?<=Latest Current Version)[^0-9]*[0-9a-zA-Z.-]+' \
                | grep -Po -m1 '[0-9.]+' \
                )
            ;;

        nodejs-lts )
            # result=$(wget -qO- \
            result=$(curl -sLN \
                https://nodejs.org/en/download/ \
                | grep -Po -m1 '(?<=Latest LTS Version)[^0-9]*[0-9a-zA-Z.-]+' \
                | grep -Po -m1 '[0-9.]+' \
                )
            ;;

        postman )
            # result=$(wget -qO- \
            result=$(curl -sLN -H "Accept: application/vnd.github.v3+json" \
                "https://dl.pstmn.io/api/version/latest?platform=linux64&channel=stable" \
                | grep -m1 "version" \
                | grep -Po '[0-9.]+'
            )
            ;;

        * )
            echo "Exiting '${0}' with code '1' because of unknown key '${1}'"
            return 1
            ;;

    esac

    if [[ -n "${result}" ]] ; then

        echo "${result}"
    else
        echo "Exiting '${0}' with code '1' because unable to get version of '$1'"
        return 1
    fi
}

main $@
