#!/bin/bash

main() {
    local version="$2"
    local result=""
    local response=""
    local truncateMax=1000

    case "$1" in

        nodejs-current )
            # result=$(wget -qO- \
            # result=$(curl -sLN \
            #     https://nodejs.org/en/feed/releases.xml \
            #     | grep '\(Current\)' \
            #     | sort -rV \
            #     | grep -Po -m1 '[0-9.]+' \
            #     )
            response=$(curl -sLN https://nodejs.org/en/feed/releases.xml)
            if [[ -n "${response}" ]] ; then
                result=$(echo "${response}" | grep '\(Current\)' | sort -rV | grep -Po -m1 '[0-9.]+')
            fi
            ;;

        nodejs-lts )
            # result=$(wget -qO- \
            # result=$(curl -sLN \
            #     https://nodejs.org/en/feed/releases.xml \
            #     | grep '\(LTS\)' \
            #     | sort -rV \
            #     | grep -Po -m1 '[0-9.]+' \
            #     )
            response=$(curl -sLN https://nodejs.org/en/feed/releases.xml)
            if [[ -n "${response}" ]] ; then
                result=$(echo "${response}" | grep '\(LTS\)' | sort -rV | grep -Po -m1 '[0-9.]+')
            fi
            ;;

        nvm )
            # result=$(wget -qO- \
            # result=$(curl -sLN -H "Accept: application/vnd.github.v3+json" \
            #     https://api.github.com/repos/nvm-sh/nvm/releases/latest \
            #     | grep -m1 "tag_name" \
            #     | grep -Po '[0-9.]+'
            # )
            response=$(curl -sLN -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/nvm-sh/nvm/releases/latest \
            )
            if [[ -n "${response}" ]] ; then
                result=$(echo "${response}" | grep -m1 "tag_name" | grep -Po '[0-9.]+')
            fi
            ;;

        postman )
            ### The 'Postman' version is locked to '10.13.6', the last one that still includes 'Scratch Pad'.
            ### The last 'Postman' version containing Scratch Pad is '10.13.6'.
            ### The first 'Postman' version not containing Scratch Pad is '10.14.2' (since May 15, 2023).
            result="10.13.6"
            
            # result=$(wget -qO- \
            # result=$(curl -sLN -H "Accept: application/vnd.github.v3+json" \
            #     "https://dl.pstmn.io/api/version/latest?platform=linux64&channel=stable" \
            #     | grep -m1 "version" \
            #     | grep -Po '[0-9.]+'
            # )
            # response=$(curl -sLN -H "Accept: application/vnd.github.v3+json" \
            #     "https://dl.pstmn.io/api/version/latest?platform=linux64&channel=stable")
            # if [[ -n "${response}" ]] ; then
            #     result=$(echo "${response}" | grep -m1 "version" | grep -Po '[0-9.]+')
            # fi 
            ;;

        vscode )
            # result=$(wget -qO- \
            # result=$(curl -sLN -H "Accept: application/vnd.github.v3+json" \
            #     https://api.github.com/repos/microsoft/vscode/releases/latest \
            #     | grep -m1 "tag_name" \
            #     | grep -Po '[0-9.]+'
            # )
            response=$(curl -sLN -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/microsoft/vscode/releases/latest \
            )
            if [[ -n "${response}" ]] ; then
                result=$(echo "${response}" | grep -m1 "tag_name" | grep -Po '[0-9.]+')
            fi
            ;;

        vscode-file )
            # result=$(wget -qO- \
            # result="$(curl -sLNI https://update.code.visualstudio.com/${version:-latest}/linux-x64/stable \
            #     | grep -Po -m1 '(?<=location: )[^\r]+'
            # )"
            # result="${result##*/}"
            response=$(curl -sLNI https://update.code.visualstudio.com/${version:-latest}/linux-x64/stable)
            if [[ -n "${response}" ]] ; then
                result=$(echo ${response} | grep -i -Po -m1 '(?<=Location: )[^\r]+')
            fi
            result="${result##*/}"
            ;;

            
        * )
            echo "Exiting '${0}' with code '1' because of unknown key '${1}'"
            return 1
            ;;

    esac

    if [[ -n "${result}" ]] ; then

        echo "${result}"
    else
        echo "ERROR: Exiting '${0}' with code '1' because unable to get version of '$1'"
        echo "ERROR: Unexpected HTTPS response (truncated to $truncateMax):"
        ### don't use quotes here
        echo ${response:0:truncateMax}
        return 1
    fi
}

main $@
